### ISSUE TITLE
Correct and Clarify Organization Repository Permissions

### ISSUE THREAD

**Issue by Bckempa** [space-ros/space-ros#120]
Several issues and PRs (e.g., https://github.com/space-ros/spaceros.org/issues/22, https://github.com/space-ros/.github/pull/2) have gotten stalled by insufficient permissions.

Based on my access thought the `space-ros` organization's ['developers' team](https://github.com/orgs/space-ros/teams/developers) there are 4 repositories that seem to have insufficient permissions:
- [`simulation`](https://github.com/space-ros/simulation)
- [`.github`](https://github.com/space-ros/.github)
- [`spaceros.org`](https://github.com/space-ros/spaceros.org)
- [`ikos`](https://github.com/space-ros/ikos)

Some of these might be intentional (like `.github`) but we should make sure developers have all intended permissions, intentionally withheld permissions are documented to keep them distinct from configuration errors, and a procedure for accessing those features requiring more trust is in place.

**Comment by ivanperez-keera** [comment]
I think the `ikos` repo should just be removed from the space-ros organization. There's no reason not to rely on NASA-SW-VnV/ikos, which is actively maintained.

**Comment by ivanperez-keera** [comment]
@Bckempa Geoffrey tells me he's cleaned up permissions and given us some rights that should be enough for day to day stuff. Please see if the issue persists, and otherwise we can ask @EzraBrooks to help us.
