### ISSUE TITLE
Inconsistent repository primary branch name

### ISSUE THREAD

**Issue by Bckempa** [space-ros/space-ros#121]
The 11 repos under the `space-ros` organization use 3 different names for their primary primary branches:
- 7 use `main`
- 3 use `master` (`.github`, `ikos`, `spaceros.org`)
- 1 uses `rolling` (looking at you, `docs`)

It isn't a requirement that they all match, and in the case of forks like `ikos` shouldn't be changed, but we should probably at least update `docs`, right? What about `.github` and `spaceros.og`? I believe those are the repos with restricted permissions (see #120), that might require escalation to the foundation.

**Comment by ivanperez-keera** [comment]
The ikos fork has to go. There's no point in having a fork of ikos within Space ROS. We can just pin the specific version from ikos' repo: https://github.com/NASA-SW-VnV/ikos.
