### ISSUE TITLE
Push `main` images for consumption by downstream repos

### ISSUE THREAD

**Issue by eholum** [space-ros/space-ros#193]
The applications in the https://github.com/space-ros/docker will require builds from main for CI runs off main. As this image is not currently tagged and pushed anywhere, we need to make it available.

I propose pushing it to the GitHub registry for this repo and making it publicly available. That way CI in the docker repo (and wherever it ends ups living) can pull directly from GH.

**Comment by franklinselva** [comment]
There is one more solution possible without pushing things to the GitHub registry or docker registry but it will force us to use Earthfiles and build the entire image from scratch.

Earthly allows referencing base images from GitHub which would tackle this problem. Essentially the base image we are trying to start from will be referenced to the Earthfile of the main repository. More information is available [here](https://docs.earthly.dev/docs/guides/best-practices#use-cross-repo-references-and-avoid-git-clone-if-possible)
