### ISSUE TITLE
Link to Contributing.md is broken

### ISSUE THREAD

**Issue by Mechazo11** [space-ros/space-ros#207]
Hi,

The link to the [CONTRIBUTING.md][https://github.com/space-ros/space-ros/blob/main/CONTRIBUTING.md] link shows a 404 not found error. This link was part of the instructions for submission in the ongoing NASA Space Sim competition.

Requesting a fix for this link so that I can confirm my submission is adhering to the Space ROS contribution protocols.

With best,
@Mechazo11

**Comment by gmacario** [comment]
Hello @Mechazo11,

If you are referring to this link in the toplevel [README.md](https://github.com/space-ros/space-ros#) of this repository

> # Contribution rules
>
> See the [contributing guide](https://github.com/space-ros/.github/blob/master/CONTRIBUTING.md) for details on how to contribute to the Space ROS project.

at least for me it works and correctly links to the existing <https://github.com/space-ros/.github/blob/master/CONTRIBUTING.md>

![image](https://github.com/user-attachments/assets/9d9dbac5-ca6a-44ae-b9fe-0a4cd8e63ea7)

**Comment by Mechazo11** [comment]
@gmacario thank you very much. I will close the issue.
