### ISSUE TITLE
clang-tidy: uninitialized va_list is copied

### ISSUE THREAD

**Issue by wjwwood** [space-ros/space-ros#4]
migrated from https://github.com/osrf/sa-spaceros/issues/13 (originally by @mjeronimo)

clang-tidy identifies several occurrences of "clang-analyzer-valist.Uninitialized" where, it claims, an uninitialized va_list is copied. These occurrences should be evaluated in the Space ROS code (vnv list) and fixed or identified as false positives.

**Comment by wjwwood** [comment]
migrated from comment by me

This one actually looks like a bug in clang-tidy. After trying to reason about it a while I went looking online and found this:

https://bugs.llvm.org/show_bug.cgi?id=41311

Our code looks pretty identical to the recommended way to use va_list and va_copy, so I think it's correct. And the folks in that thread have the exact same issue with very similar code. I am not 100% sure that this is the same issue we have currently, but I am quite sure the code is safe as written.

**Comment by ivanperez-keera** [comment]
We are preparing an official release of Space ROS. This feature, already completed, will be considered part of that release, so it will be moved to the corresponding milestone.
