### ISSUE TITLE
Integrate `ament_cobra` into the Space ROS build system

### ISSUE THREAD

**Issue by mjeronimo** [space-ros/space-ros#48]
Enable the AutoSAR checks (only) with SARIF output.

**Comment by ivanperez-keera** [comment]
We are moving this to a different milestone.

**Comment by xfiderek** [comment]
We have the commit with the same name and summary as this issue https://github.com/ament/ament_cobra/commit/7f24461cdfeb7cb7efbe83b6a76bc9f8d2e6588d.

I guess we can close it @ivanperez-keera

**Comment by ivanperez-keera** [comment]
Awesome, @xfiderek . Thanks!
