### ISSUE TITLE
Review FRET and figure out how to integrate it and Doorstop

### ISSUE THREAD

**Issue by gbiggs** [space-ros/space-ros#51]
[FRET](https://github.com/NASA-SW-VnV/fret) is a tool developed by NASA for the production of formally-verifiable requirements. There is great interest in using it for Space ROS due to its ability to check that requirements are correct - something that is useful when non-requirements-experts are going to be producing requirements.

We need to learn how to use it and perform an evaluation of its usefulness.

We need to determine if it is suitable for all of our requirements needs, or should be used in conjunction with another tool such as Doorstop. If it needs to be used in conjunction with another tool, then we need to figure out how to integrate the tools.

**Comment by mjeronimo** [comment]
We have decided to use a combination of FRET and Doorstop and have developed a unified file format that each of them can read.
