### ISSUE TITLE
clang-tidy: Virtual dispatch

### ISSUE THREAD

**Issue by wjwwood** [space-ros/space-ros#8]
migrated from https://github.com/osrf/sa-spaceros/issues/8 (originally by @mjeronimo)

clang-tidy identifies several occurrences of bypassing virtual dispatch during object construction and destruction. For example,

```
"<symbol>” during construction bypasses virtual dispatch [clang-analyzer-optin.cplusplus.VirtualCall]"
"<symbol>” during destruction bypasses virtual dispatch [clang-analyzer-optin.cplusplus.VirtualCall]"
```
We should evaluate these occurrences in the Space ROS source code (vnv list) to fix or identify as a false positive.

**Comment by ivanperez-keera** [comment]
We are preparing an official release of Space ROS. This feature, already completed, will be considered part of that release, so it will be moved to the corresponding milestone.
