### ISSUE TITLE
Automatic commits from CI job

### ISSUE THREAD

**Issue by ivanperez-keera** [space-ros/space-ros#88]
The current CI job is automatically committing changes to the repo. For example, the current HEAD shows:

<img width="800" alt="image" src="https://github.com/space-ros/space-ros/assets/1162320/27b401fb-ddcc-4cd4-944a-0c1bf8e33d05">

I pushed a branch to the space-ros repo and the CI job automatically added commits to that branch unrelated to my change (also without referencing any issue).

It seems that those are version bumps. Before bumping the version numbers of dependencies, I'd like to know that Space ROS works with those versions. Does the current CI setup check that everything is working with the new versions?

Could we address this need in a way that does not interfere with our workflow and does not add uncontrolled commits, while minimizing the amount of work and oversight required?

**Comment by ivanperez-keera** [comment]
The reason for these commits is:

https://github.com/space-ros/space-ros/blob/3418a46c3380e5250ad1185808a6295c4d306209/.github/workflows/vcs-repos.yaml#L30-L34

**Comment by EzraBrooks** [comment]
I'm okay with just removing this. Without delving too deep into my strong opinions on the way ROS projects tend to do version control, I very much don't like this. I'll open a PR.
